const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, 'dist');
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

const whatsapp = 'https://wa.me/541176689413';
const cities = [
  { slug:'buenos-aires', name:'Buenos Aires', country:'Argentina', image:'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1800&q=85', intro:'Tango, arquitectura, cafés históricos y barrios con personalidad propia.', picks:['Caminar por San Telmo y Plaza de Mayo','Descubrir Palermo y sus restaurantes','Vivir una noche de tango','Recorrer Recoleta y su arquitectura'] },
  { slug:'madrid', name:'Madrid', country:'España', image:'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1800&q=85', intro:'Arte, tapas, parques y una energía que se disfruta a cualquier hora.', picks:['Visitar el Museo del Prado','Pasear por el Retiro','Probar tapas en La Latina','Recorrer el Madrid de los Austrias'] },
  { slug:'barcelona', name:'Barcelona', country:'España', image:'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1800&q=85', intro:'Modernismo, Mediterráneo, mercados y barrios llenos de historia.', picks:['Conocer la Sagrada Familia','Recorrer el Barrio Gótico','Pasear por la Barceloneta','Descubrir el Park Güell'] },
  { slug:'roma', name:'Roma', country:'Italia', image:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1800&q=85', intro:'Historia viva, plazas inolvidables y sabores que justifican cada paseo.', picks:['Visitar el Coliseo y el Foro Romano','Recorrer el Vaticano','Lanzar una moneda en la Fontana di Trevi','Comer en una trattoria de Trastevere'] },
  { slug:'lisboa', name:'Lisboa', country:'Portugal', image:'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1800&q=85', intro:'Miradores, tranvías, azulejos y el encanto único del río Tajo.', picks:['Subir al barrio de Alfama','Conocer la Torre de Belém','Probar pasteles de nata','Ver el atardecer desde un mirador'] },
  { slug:'medellin', name:'Medellín', country:'Colombia', image:'https://images.unsplash.com/photo-1599413987323-b2f97e3efc8f?auto=format&fit=crop&w=1800&q=85', intro:'Innovación, naturaleza, cultura urbana y la calidez de su gente.', picks:['Conocer la Comuna 13','Subir al Metrocable','Visitar Plaza Botero','Hacer una excursión a Guatapé'] },
  { slug:'rio-de-janeiro', name:'Río de Janeiro', country:'Brasil', image:'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1800&q=85', intro:'Playas, montañas, música y algunas de las vistas más famosas del mundo.', picks:['Subir al Cristo Redentor','Disfrutar Copacabana e Ipanema','Conocer el Pan de Azúcar','Recorrer Santa Teresa'] }
];

const css = `:root{--cream:#fffbf0;--ink:#16302d;--teal:#0f766e;--teal2:#115e59;--white:#fff;--muted:#5d6b68}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--cream);color:var(--ink);line-height:1.6}a{color:inherit}.nav{height:70px;display:flex;align-items:center;justify-content:space-between;padding:0 6%;background:rgba(255,251,240,.96);position:sticky;top:0;z-index:5;border-bottom:1px solid #e8e1d2}.brand{font-size:1.45rem;font-weight:900;text-decoration:none}.brand span{color:var(--teal)}.navlinks{display:flex;gap:20px;font-size:.93rem}.navlinks a{text-decoration:none}.hero{min-height:72vh;display:grid;place-items:center;text-align:center;color:#fff;background:linear-gradient(#062d2a80,#062d2ab5),var(--hero) center/cover;padding:80px 20px}.hero small{text-transform:uppercase;letter-spacing:.18em;font-weight:800}.hero h1{font-size:clamp(2.8rem,8vw,6.2rem);line-height:1;margin:.16em 0}.hero p{font-size:clamp(1.05rem,2.2vw,1.35rem);max-width:720px;margin:18px auto 30px}.wa{display:inline-flex;align-items:center;justify-content:center;background:#20a568;color:#fff;padding:18px 28px;border-radius:15px;font-weight:900;text-decoration:none;box-shadow:0 12px 30px #062d2a40}.wa:hover{transform:translateY(-2px)}.section{max-width:1120px;margin:auto;padding:72px 22px}.eyebrow{color:var(--teal);font-weight:900;text-transform:uppercase;letter-spacing:.12em}.section h2{font-size:clamp(2rem,4vw,3.2rem);line-height:1.1;margin:.25em 0}.lead{color:var(--muted);max-width:760px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px;margin-top:35px}.card{background:#fff;border:1px solid #e9e1d2;border-radius:18px;padding:25px;box-shadow:0 8px 24px #31534f0c}.card b{display:block;font-size:1.15rem;margin-bottom:5px}.cities{grid-template-columns:repeat(3,1fr)}.city{min-height:220px;color:#fff;display:flex;align-items:flex-end;background:linear-gradient(#0002,#052e2bb0),var(--bg) center/cover;text-decoration:none}.city b{font-size:1.45rem}.steps{counter-reset:n}.steps .card:before{counter-increment:n;content:counter(n);display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--teal);color:#fff;font-weight:900;margin-bottom:14px}.notice{background:#e5f2ef;border-left:5px solid var(--teal);padding:18px;border-radius:10px;margin-top:28px}.cta{text-align:center;background:var(--teal);color:#fff;border-radius:25px;padding:55px 25px}.cta .wa{background:#fff;color:var(--teal)}footer{background:#102c29;color:#d9e7e4;padding:40px 6%}.foot{max-width:1120px;margin:auto;display:flex;justify-content:space-between;gap:30px;flex-wrap:wrap}.foot a{color:#fff;margin-right:15px}.legal{max-width:850px;margin:60px auto;padding:0 22px}.legal h1{font-size:2.7rem}.legal h2{margin-top:32px}@media(max-width:760px){.navlinks{display:none}.grid,.cities{grid-template-columns:1fr}.hero{min-height:68vh}.section{padding:52px 20px}}`;
fs.writeFileSync(path.join(out, 'style.css'), css);

function layout({title,description,body,canonical=''}){
 return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://chebot.chat${canonical}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><link rel="stylesheet" href="/style.css"></head><body><nav class="nav"><a class="brand" href="/">Che<span>bot</span></a><div class="navlinks"><a href="/#ciudades">Ciudades</a><a href="/como-funciona">Cómo funciona</a><a href="/contacto">Contacto</a></div></nav>${body}<footer><div class="foot"><div><b>Chebot</b><br>Tu guía de viaje por WhatsApp.</div><div><a href="/privacidad">Privacidad</a><a href="/terminos">Términos</a><a href="/contacto">Contacto</a></div><small>© ${new Date().getFullYear()} Chebot</small></div></footer></body></html>`;
}
function writePage(slug, html){const dir=path.join(out,slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html)}

const cityCards=cities.map(c=>`<a class="card city" style="--bg:url('${c.image}')" href="/${c.slug}"><div><small>${c.country}</small><b>${c.name}</b></div></a>`).join('');
fs.writeFileSync(path.join(out,'index.html'),layout({title:'Chebot | Tu guía turística por WhatsApp',description:'Descubrí qué hacer, dónde comer y cómo moverte en siete grandes ciudades con la ayuda de Chebot por WhatsApp.',body:`<header class="hero" style="--hero:url('${cities[6].image}')"><div><small>Tu próximo viaje empieza acá</small><h1>Viajá mejor<br>con Chebot</h1><p>Orientación turística rápida y sencilla directamente por WhatsApp.</p><a class="wa" href="${whatsapp}?text=${encodeURIComponent('Hola Chebot, quiero planificar mi viaje')}" rel="noopener">Hablar con Chebot en WhatsApp</a></div></header><main><section class="section" id="ciudades"><span class="eyebrow">Elegí tu destino</span><h2>Siete ciudades, un solo guía</h2><p class="lead">Ideas para organizar tu viaje y encontrar experiencias, gastronomía, alojamiento y transporte.</p><div class="grid cities">${cityCards}</div></section><section class="section"><div class="cta"><h2>¿No sabés por dónde empezar?</h2><p>Contale a Chebot qué ciudad visitarás y qué tipo de experiencia buscás.</p><a class="wa" href="${whatsapp}?text=${encodeURIComponent('Hola Chebot, necesito ayuda para elegir mi destino')}" rel="noopener">Consultar gratis por WhatsApp</a></div></section></main>`,canonical:'/'}));

cities.forEach(c=>writePage(c.slug,layout({title:`Qué hacer en ${c.name} | Chebot`,description:`Guía de ${c.name}: lugares imprescindibles, gastronomía, alojamiento y transporte. Consultá a Chebot por WhatsApp.`,canonical:`/${c.slug}`,body:`<header class="hero" style="--hero:url('${c.image}')"><div><small>${c.country}</small><h1>${c.name}</h1><p>${c.intro}</p><a class="wa" href="${whatsapp}?text=${encodeURIComponent('Hola Chebot, quiero información de '+c.name)}" rel="noopener">Hablar con Chebot en WhatsApp</a></div></header><main><section class="section"><span class="eyebrow">Primera visita</span><h2>Ideas para descubrir ${c.name}</h2><p class="lead">Una selección inicial para inspirarte. Chebot puede ayudarte a ordenar las opciones según tus días, intereses y presupuesto.</p><div class="grid">${c.picks.map(x=>`<article class="card"><b>${x}</b><span>Pedile a Chebot horarios, zonas recomendadas y consejos para organizar la visita.</span></article>`).join('')}</div><div class="notice"><b>Transparencia:</b> algunos enlaces recomendados podrán ser enlaces de afiliados. Si reservás mediante ellos, Chebot podría recibir una comisión sin costo adicional para vos.</div></section><section class="section"><div class="cta"><h2>Armá tu plan para ${c.name}</h2><p>Escribinos por WhatsApp y contanos qué querés hacer.</p><a class="wa" href="${whatsapp}?text=${encodeURIComponent('Hola Chebot, ayúdame a organizar mi viaje a '+c.name)}" rel="noopener">Consultar a Chebot</a></div></section></main>`}))); 

writePage('como-funciona',layout({title:'Cómo funciona Chebot',description:'Conocé cómo usar Chebot para obtener orientación turística mediante WhatsApp.',canonical:'/como-funciona',body:`<main class="section"><span class="eyebrow">Simple y directo</span><h2>Tu guía de viaje en tres pasos</h2><div class="grid steps"><article class="card"><b>Elegí una ciudad</b>Buenos Aires, Madrid, Barcelona, Roma, Lisboa, Medellín o Río de Janeiro.</article><article class="card"><b>Escribí por WhatsApp</b>Contanos si buscás actividades, comida, alojamiento o transporte.</article><article class="card"><b>Recibí orientación</b>Chebot te acerca ideas y enlaces útiles para organizar el viaje.</article></div><div class="notice">Chebot brinda información turística general. Verificá horarios, precios, disponibilidad y condiciones directamente con cada proveedor antes de reservar.</div></main>`}));
writePage('contacto',layout({title:'Contacto | Chebot',description:'Contactá al equipo de Chebot.',canonical:'/contacto',body:`<main class="legal"><h1>Contacto</h1><p>Para consultas sobre Chebot, sugerencias, correcciones o solicitudes relacionadas con tus datos, escribinos por WhatsApp.</p><p><a class="wa" href="${whatsapp}?text=${encodeURIComponent('Hola Chebot, quiero comunicarme con el equipo')}" rel="noopener">Contactar por WhatsApp</a></p><p>Proyecto: Chebot · Argentina</p></main>`}));
writePage('privacidad',layout({title:'Política de privacidad | Chebot',description:'Política de privacidad de Chebot.',canonical:'/privacidad',body:`<main class="legal"><h1>Política de privacidad</h1><p>Última actualización: 28 de agosto de 2026.</p><h2>Información que recibimos</h2><p>Cuando contactás a Chebot por WhatsApp, recibimos el número asociado a tu cuenta y el contenido de los mensajes que enviás. También podemos recibir datos técnicos básicos de navegación del sitio.</p><h2>Cómo usamos la información</h2><p>La utilizamos para responder consultas, mejorar el servicio, prevenir abusos y cumplir obligaciones legales. No vendemos datos personales.</p><h2>Servicios externos</h2><p>Chebot utiliza proveedores tecnológicos para operar el sitio y la mensajería. Al abrir enlaces externos se aplican las políticas del proveedor correspondiente.</p><h2>Tus opciones</h2><p>Podés solicitar acceso, corrección o eliminación de tus datos desde nuestra página de contacto.</p></main>`}));
writePage('terminos',layout({title:'Términos y aviso de afiliados | Chebot',description:'Condiciones de uso y aviso de afiliados de Chebot.',canonical:'/terminos',body:`<main class="legal"><h1>Términos y aviso de afiliados</h1><p>Chebot ofrece orientación turística general y no actúa como agencia de viajes ni garantiza la disponibilidad, calidad o condiciones de servicios de terceros.</p><h2>Reservas y terceros</h2><p>Las compras o reservas se realizan directamente con proveedores externos. Antes de contratar, revisá precios, horarios, cancelaciones y condiciones en el sitio del proveedor.</p><h2>Enlaces de afiliados</h2><p>Algunos enlaces pueden ser de afiliados. Chebot podría recibir una comisión cuando una persona realiza una reserva a través de ellos, sin incrementar el precio para el usuario. Las recomendaciones buscan ser relevantes y esta posible comisión no modifica las condiciones ofrecidas por el proveedor.</p><h2>Uso responsable</h2><p>No uses el servicio para actividades ilícitas, abusivas o que afecten su funcionamiento.</p></main>`}));

const sitemap=['','como-funciona','contacto','privacidad','terminos',...cities.map(c=>c.slug)].map(s=>`<url><loc>https://chebot.chat/${s}</loc></url>`).join('');
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${sitemap}</urlset>`);
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://chebot.chat/sitemap.xml\n');
