const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, 'dist');
const managerDir = path.join(out, 'manager');
const indexFile = path.join(managerDir, 'index.html');

const supabaseUrl = String(process.env.SUPABASE_URL || '').replace(/\/+$/, '');
const publishableKey = String(process.env.SUPABASE_PUBLISHABLE_KEY || '');
const backendSessionUrl =
  'https://chebot-backend-git-concierge-v3-design-chebot.vercel.app/api/concierge/manager/session';

if (!supabaseUrl) {
  throw new Error('SUPABASE_URL is required for Manager Web Preview.');
}
if (!publishableKey) {
  throw new Error('SUPABASE_PUBLISHABLE_KEY is required for Manager Web Preview.');
}
if (!fs.existsSync(indexFile)) {
  throw new Error('dist/manager/index.html was not generated by build.js.');
}

const css = `
.manager-auth-pending .shell{display:none!important}
.manager-auth-screen{min-height:100vh;display:grid;place-items:center;padding:28px;background:#f7f4ec;color:#16302d}
.manager-auth-card{width:min(440px,100%);background:#fff;border:1px solid #e5ddd0;border-radius:20px;padding:26px;box-shadow:0 14px 40px #173d3814}
.manager-auth-brand{font-size:1.35rem;font-weight:900;margin-bottom:5px}
.manager-auth-brand span{color:#0f766e}
.manager-auth-kicker{font-size:.78rem;text-transform:uppercase;letter-spacing:.11em;color:#0f766e;font-weight:900}
.manager-auth-card h1{font-size:1.75rem;line-height:1.1;margin:8px 0}
.manager-auth-card p{color:#61706d;line-height:1.55}
.manager-auth-field{display:grid;gap:6px;margin-top:14px}
.manager-auth-field label{font-weight:850;font-size:.9rem}
.manager-auth-field input{width:100%;padding:12px 13px;border:1px solid #b9c5c2;border-radius:11px;font:inherit;background:#fff;color:#16302d}
.manager-auth-submit,.manager-auth-logout{border:0;border-radius:11px;font:inherit;font-weight:900;cursor:pointer}
.manager-auth-submit{width:100%;margin-top:18px;padding:13px 16px;background:#0f766e;color:#fff}
.manager-auth-submit:disabled{opacity:.6;cursor:wait}
.manager-auth-status{min-height:24px;margin-top:12px;font-size:.88rem;font-weight:800}
.manager-auth-status.error{color:#8a3325}
.manager-auth-status.ok{color:#0f766e}
.manager-auth-foot{font-size:.78rem!important;margin-top:18px!important}
.manager-auth-logout{padding:8px 11px;background:#fff;border:1px solid #cfd8d5;color:#16302d;margin-left:8px}
.manager-auth-session{display:inline-flex;align-items:center;gap:6px;font-size:.82rem;color:#61706d}
`;

fs.writeFileSync(path.join(managerDir, 'manager-auth.css'), css);

const browserJs = `
(() => {
  'use strict';

  const SUPABASE_URL = ${JSON.stringify(supabaseUrl)};
  const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishableKey)};
  const BACKEND_SESSION_URL = ${JSON.stringify(backendSessionUrl)};
  const TOKEN_KEY = 'chebot_manager_preview_access_token';

  const authScreen = document.getElementById('manager-auth');
  const form = document.getElementById('manager-login-form');
  const email = document.getElementById('manager-email');
  const password = document.getElementById('manager-password');
  const status = document.getElementById('manager-auth-status');
  const submit = document.getElementById('manager-login-submit');
  const logout = document.getElementById('manager-logout');
  const sessionLabel = document.getElementById('manager-session-label');
  const accountLabel = document.getElementById('manager-account-label');

  function setStatus(message, kind) {
    status.textContent = message || '';
    status.className = 'manager-auth-status' + (kind ? ' ' + kind : '');
  }

  function clearToken() {
    sessionStorage.removeItem(TOKEN_KEY);
  }

  function showLogin(message) {
    clearToken();
    document.body.classList.add('manager-auth-pending');
    authScreen.hidden = false;
    if (message) setStatus(message, 'error');
    password.value = '';
    setTimeout(() => email.focus(), 0);
  }

  function showPanel(session) {
    authScreen.hidden = true;
    document.body.classList.remove('manager-auth-pending');
    const role = session && session.role ? String(session.role) : 'manager';
    sessionLabel.textContent = 'Sesión verificada · ' + role;
    accountLabel.textContent = 'Chebot Concierge · ' + role;
  }

  async function verifyManagerSession(accessToken) {
    const response = await fetch(BACKEND_SESSION_URL, {
      method: 'GET',
      mode: 'cors',
      cache: 'no-store',
      headers: {
        Authorization: 'Bearer ' + accessToken,
        Accept: 'application/json'
      }
    });

    let body = null;
    try { body = await response.json(); } catch (_) {}

    if (!response.ok || !body || body.ok !== true || !body.session) {
      const error = body && body.error ? String(body.error) : 'MANAGER_SESSION_DENIED';
      const e = new Error(error);
      e.code = error;
      throw e;
    }

    return body.session;
  }

  async function signIn(loginEmail, loginPassword) {
    const response = await fetch(
      SUPABASE_URL + '/auth/v1/token?grant_type=password',
      {
        method: 'POST',
        cache: 'no-store',
        headers: {
          apikey: SUPABASE_PUBLISHABLE_KEY,
          'Content-Type': 'application/json',
          Accept: 'application/json'
        },
        body: JSON.stringify({
          email: loginEmail,
          password: loginPassword
        })
      }
    );

    let body = null;
    try { body = await response.json(); } catch (_) {}

    if (!response.ok || !body || !body.access_token) {
      const e = new Error('LOGIN_INVALID');
      e.code = 'LOGIN_INVALID';
      throw e;
    }

    return body.access_token;
  }

  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    submit.disabled = true;
    setStatus('Verificando acceso…');

    try {
      const accessToken = await signIn(email.value.trim(), password.value);
      const managerSession = await verifyManagerSession(accessToken);
      sessionStorage.setItem(TOKEN_KEY, accessToken);
      password.value = '';
      setStatus('', '');
      showPanel(managerSession);
    } catch (error) {
      clearToken();

      if (error && error.code === 'LOGIN_INVALID') {
        setStatus('Email o contraseña incorrectos.', 'error');
      } else if (error && error.code === 'WEB_IDENTITY_UNKNOWN') {
        setStatus('El usuario existe, pero todavía no está vinculado a un manager de Concierge.', 'error');
      } else if (error && error.code === 'MANAGER_MEMBER_NOT_ACTIVE') {
        setStatus('El acceso de este manager no está activo.', 'error');
      } else {
        setStatus('No se pudo validar el acceso. Revisaremos la conexión antes de continuar.', 'error');
      }
    } finally {
      submit.disabled = false;
    }
  });

  logout.addEventListener('click', () => {
    showLogin('');
  });

  (async () => {
    const existingToken = sessionStorage.getItem(TOKEN_KEY);
    if (!existingToken) {
      showLogin('');
      return;
    }

    setStatus('Restaurando sesión…');

    try {
      const managerSession = await verifyManagerSession(existingToken);
      setStatus('', '');
      showPanel(managerSession);
    } catch (_) {
      showLogin('Tu sesión venció. Iniciá sesión nuevamente.');
    }
  })();
})();
`;

fs.writeFileSync(path.join(managerDir, 'manager-auth.js'), browserJs);

let html = fs.readFileSync(indexFile, 'utf8');

html = html.replace(
  '<link rel="stylesheet" href="/manager/manager.css">',
  '<link rel="stylesheet" href="/manager/manager.css">\n  <link rel="stylesheet" href="/manager/manager-auth.css">'
);

html = html.replace(
  '<body>',
  `<body class="manager-auth-pending">
  <section class="manager-auth-screen" id="manager-auth" aria-labelledby="manager-login-title">
    <div class="manager-auth-card">
      <div class="manager-auth-brand">Che<span>bot</span> Concierge</div>
      <div class="manager-auth-kicker">Manager Web V1 · Beta interna</div>
      <h1 id="manager-login-title">Ingresá a tu panel</h1>
      <p>Acceso exclusivo para managers autorizados de Chebot Concierge.</p>
      <form id="manager-login-form" autocomplete="on">
        <div class="manager-auth-field">
          <label for="manager-email">Email</label>
          <input id="manager-email" name="email" type="email" autocomplete="username" required>
        </div>
        <div class="manager-auth-field">
          <label for="manager-password">Contraseña</label>
          <input id="manager-password" name="password" type="password" autocomplete="current-password" required>
        </div>
        <button class="manager-auth-submit" id="manager-login-submit" type="submit">Ingresar</button>
        <div class="manager-auth-status" id="manager-auth-status" role="status" aria-live="polite"></div>
      </form>
      <p class="manager-auth-foot">Preview aislada. La contraseña se envía directamente a Supabase Auth y no se guarda en el sitio.</p>
    </div>
  </section>`
);

html = html.replace(
  '<strong>Vicky & Maty · Demo</strong>\n        <span class="pill">Modo manager · WhatsApp-first</span>',
  `<strong id="manager-account-label">Chebot Concierge · Manager</strong>
        <div><span class="manager-auth-session" id="manager-session-label">Sesión verificada</span><button class="manager-auth-logout" id="manager-logout" type="button">Salir</button></div>`
);

html = html.replace(
  '<b>Preview interna:</b> interfaz ficticia y aislada. El acceso real, autenticación y datos vivos se conectarán al backend Concierge en una etapa posterior.',
  '<b>Preview autenticada:</b> el acceso ya se valida contra Chebot Concierge Dev. El contenido del panel sigue siendo ficticio hasta conectar las vistas de datos reales.'
);

html = html.replace(
  '</body>',
  '  <script src="/manager/manager-auth.js" defer></script>\n</body>'
);

fs.writeFileSync(indexFile, html);
console.log('Manager Web auth gate installed.');
