const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, 'dist');
const managerDir = path.join(out, 'manager');
const indexFile = path.join(managerDir, 'index.html');

const supabaseUrl = String(process.env.SUPABASE_URL || '').replace(/\/+$/, '');
const publishableKey = String(process.env.SUPABASE_PUBLISHABLE_KEY || '');
const backendSessionUrl =
  'https://chebot-backend-git-concierge-v3-design-chebot.vercel.app/api/concierge/manager/session';
const backendPropertiesUrl =
  'https://chebot-backend-git-concierge-v3-design-chebot.vercel.app/api/concierge/manager/properties';
const backendStaysUrl =
  'https://chebot-backend-git-concierge-v3-design-chebot.vercel.app/api/concierge/manager/stays';

if (!supabaseUrl) {
  throw new Error('SUPABASE_URL is required for Manager Web Preview.');
}
if (!publishableKey) {
  throw new Error('SUPABASE_PUBLISHABLE_KEY is required for Manager Web Preview.');
}
if (!fs.existsSync(indexFile)) {
  throw new Error('dist/manager/index.html was not generated by build.js.');
}

const css = `
.manager-auth-pending .shell{display:none!important}
.manager-auth-screen[hidden]{display:none!important}
.manager-auth-screen{min-height:100vh;display:grid;place-items:center;padding:28px;background:#f7f4ec;color:#16302d}
.manager-auth-card{width:min(440px,100%);background:#fff;border:1px solid #e5ddd0;border-radius:20px;padding:26px;box-shadow:0 14px 40px #173d3814}
.manager-auth-brand{font-size:1.35rem;font-weight:900;margin-bottom:5px}
.manager-auth-brand span{color:#0f766e}
.manager-auth-kicker{font-size:.78rem;text-transform:uppercase;letter-spacing:.11em;color:#0f766e;font-weight:900}
.manager-auth-card h1{font-size:1.75rem;line-height:1.1;margin:8px 0}
.manager-auth-card p{color:#61706d;line-height:1.55}
.manager-auth-field{display:grid;gap:6px;margin-top:14px}
.manager-auth-field label{font-weight:850;font-size:.9rem}
.manager-auth-field input{width:100%;padding:12px 13px;border:1px solid #b9c5c2;border-radius:11px;font:inherit;background:#fff;color:#16302d}
.manager-auth-submit,.manager-auth-logout{border:0;border-radius:11px;font:inherit;font-weight:900;cursor:pointer}
.manager-auth-submit{width:100%;margin-top:18px;padding:13px 16px;background:#0f766e;color:#fff}
.manager-auth-submit:disabled{opacity:.6;cursor:wait}
.manager-auth-status{min-height:24px;margin-top:12px;font-size:.88rem;font-weight:800}
.manager-auth-status.error{color:#8a3325}
.manager-auth-status.ok{color:#0f766e}
.manager-auth-foot{font-size:.78rem!important;margin-top:18px!important}
.manager-auth-logout{padding:8px 11px;background:#fff;border:1px solid #cfd8d5;color:#16302d;margin-left:8px}
.manager-auth-session{display:inline-flex;align-items:center;gap:6px;font-size:.82rem;color:#61706d}
`;

fs.writeFileSync(path.join(managerDir, 'manager-auth.css'), css);

const browserJs = `
(() => {
  'use strict';

  const SUPABASE_URL = ${JSON.stringify(supabaseUrl)};
  const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishableKey)};
  const BACKEND_SESSION_URL = ${JSON.stringify(backendSessionUrl)};
  const BACKEND_PROPERTIES_URL = ${JSON.stringify(backendPropertiesUrl)};
  const BACKEND_STAYS_URL = ${JSON.stringify(backendStaysUrl)};
  const TOKEN_KEY = 'chebot_manager_preview_access_token';

  const authScreen = document.getElementById('manager-auth');
  const form = document.getElementById('manager-login-form');
  const email = document.getElementById('manager-email');
  const password = document.getElementById('manager-password');
  const status = document.getElementById('manager-auth-status');
  const submit = document.getElementById('manager-login-submit');
  const logout = document.getElementById('manager-logout');
  const sessionLabel = document.getElementById('manager-session-label');
  const accountLabel = document.getElementById('manager-account-label');

  function setStatus(message, kind) {
    status.textContent = message || '';
    status.className = 'manager-auth-status' + (kind ? ' ' + kind : '');
  }

  function clearToken() {
    sessionStorage.removeItem(TOKEN_KEY);
  }

  function showLogin(message) {
    clearToken();
    document.body.classList.add('manager-auth-pending');
    authScreen.hidden = false;
    if (message) setStatus(message, 'error');
    password.value = '';
    setTimeout(() => email.focus(), 0);
  }

  function showPanel(session) {
    authScreen.hidden = true;
    document.body.classList.remove('manager-auth-pending');
    const role = session && session.role ? String(session.role) : 'manager';
    sessionLabel.textContent = 'Sesión verificada · ' + role;
    accountLabel.textContent = 'Chebot Concierge · ' + role;
  }

  function propertyStatusLabel(statusValue) {
    const labels = {
      active: 'Activa',
      ready_for_review: 'Lista para revisión',
      draft: 'Borrador',
      paused: 'Pausada',
      archived: 'Archivada'
    };
    return labels[String(statusValue || '')] || String(statusValue || 'Sin estado');
  }

  function renderPropertyMetric(properties) {
    const metrics = Array.from(document.querySelectorAll('.metric'));
    const card = metrics.find((item) => {
      const small = item.querySelector('small');
      return small && small.textContent.trim() === 'Propiedades activas';
    });

    if (!card) return;

    const activeCount = properties.filter((property) => property.property_status === 'active').length;
    const totalCount = properties.length;
    const number = card.querySelector('b');
    const tag = card.querySelector('.tag');

    if (number) number.textContent = String(activeCount);
    if (tag) {
      tag.textContent = totalCount === 1 ? '1 propiedad real' : totalCount + ' propiedades reales';
      tag.className = 'tag';
    }
  }

  function renderProperties(properties) {
    const list = document.querySelector('#propiedades .list');
    if (!list) return;

    list.replaceChildren();

    if (!properties.length) {
      const empty = document.createElement('article');
      empty.className = 'card';
      const title = document.createElement('b');
      title.textContent = 'Sin propiedades disponibles';
      const detail = document.createElement('p');
      detail.className = 'muted';
      detail.textContent = 'No hay propiedades autorizadas para esta cuenta.';
      empty.append(title, detail);
      list.appendChild(empty);
      renderPropertyMetric([]);
      return;
    }

    properties.forEach((property) => {
      const row = document.createElement('article');
      row.className = 'row';

      const identity = document.createElement('div');
      const name = document.createElement('b');
      name.textContent = String(property.internal_name || 'Propiedad');
      const source = document.createElement('div');
      source.className = 'muted';
      source.textContent = 'Concierge Dev · dato real';
      identity.append(name, source);

      const statusTag = document.createElement('span');
      statusTag.className =
        property.property_status === 'active'
          ? 'tag'
          : property.property_status === 'ready_for_review'
            ? 'tag warn'
            : 'tag';
      statusTag.textContent = propertyStatusLabel(property.property_status);

      const role = document.createElement('span');
      role.textContent = 'Acceso: ' + String(property.member_role || 'manager');

      const enabledPermissions = [
        property.can_manage_stays && 'estadías',
        property.can_manage_incidents && 'incidencias',
        property.can_approve_requests && 'solicitudes',
        property.can_manage_knowledge && 'conocimiento',
        property.can_manage_secrets && 'secretos',
        property.can_manage_team && 'equipo'
      ].filter(Boolean);

      const permissions = document.createElement('span');
      permissions.textContent = enabledPermissions.length
        ? 'Permisos: ' + enabledPermissions.join(', ')
        : 'Sin permisos operativos';

      row.append(identity, statusTag, role, permissions);
      list.appendChild(row);
    });

    renderPropertyMetric(properties);
  }

  function renderPropertiesError() {
    const list = document.querySelector('#propiedades .list');
    if (!list) return;
    list.replaceChildren();

    const errorCard = document.createElement('article');
    errorCard.className = 'card';
    const title = document.createElement('b');
    title.textContent = 'No pudimos cargar las propiedades';
    const detail = document.createElement('p');
    detail.className = 'muted';
    detail.textContent = 'La sesión sigue activa. Reintentá recargando la página.';
    errorCard.append(title, detail);
    list.appendChild(errorCard);
  }

  async function loadManagerProperties(accessToken) {
    const response = await fetch(BACKEND_PROPERTIES_URL, {
      method: 'GET',
      mode: 'cors',
      cache: 'no-store',
      headers: {
        Authorization: 'Bearer ' + accessToken,
        Accept: 'application/json'
      }
    });

    let body = null;
    try { body = await response.json(); } catch (_) {}

    if (!response.ok || !body || body.ok !== true || !Array.isArray(body.properties)) {
      const error = body && body.error ? String(body.error) : 'MANAGER_PROPERTIES_LOAD_FAILED';
      const e = new Error(error);
      e.code = error;
      throw e;
    }

    renderProperties(body.properties);
    return body.properties;
  }

  function stayStatusLabel(statusValue) {
    const labels = {
      draft: 'Borrador',
      scheduled: 'Programada',
      active: 'Activa',
      completed: 'Finalizada',
      cancelled: 'Cancelada',
      revoked: 'Revocada'
    };
    return labels[String(statusValue || '')] || String(statusValue || 'Sin estado');
  }

  function stayStatusClass(statusValue) {
    const value = String(statusValue || '');
    if (value === 'scheduled' || value === 'active' || value === 'completed') return 'tag';
    if (value === 'draft') return 'tag warn';
    return 'tag danger';
  }

  function formatStayDate(value) {
    if (!value) return '—';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return String(value);

    return new Intl.DateTimeFormat('es-AR', {
      timeZone: 'America/Argentina/Buenos_Aires',
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false
    }).format(date);
  }

  function renderStays(stays) {
    const list = document.querySelector('#estadias .list');
    if (!list) return;

    list.replaceChildren();

    if (!stays.length) {
      const empty = document.createElement('article');
      empty.className = 'card';
      const title = document.createElement('b');
      title.textContent = 'Sin estadías';
      const detail = document.createElement('p');
      detail.className = 'muted';
      detail.textContent = 'No hay estadías disponibles en las propiedades autorizadas.';
      empty.append(title, detail);
      list.appendChild(empty);
      return;
    }

    stays.forEach((stay) => {
      const row = document.createElement('article');
      row.className = 'row';

      const identity = document.createElement('div');
      const name = document.createElement('b');
      name.textContent = String(stay.property_internal_name || 'Propiedad');
      const source = document.createElement('div');
      source.className = 'muted';
      source.textContent = 'Concierge Dev · estadía real';
      identity.append(name, source);

      const dates = document.createElement('span');
      dates.textContent =
        formatStayDate(stay.check_in_at) + ' → ' + formatStayDate(stay.check_out_at);

      const statusTag = document.createElement('span');
      statusTag.className = stayStatusClass(stay.status);
      statusTag.textContent = stayStatusLabel(stay.status);

      const access = document.createElement('span');
      access.textContent =
        'Acceso: ' + formatStayDate(stay.access_from) + ' → ' + formatStayDate(stay.access_until);

      row.append(identity, dates, statusTag, access);
      list.appendChild(row);
    });
  }

  function renderStaysError() {
    const list = document.querySelector('#estadias .list');
    if (!list) return;
    list.replaceChildren();

    const errorCard = document.createElement('article');
    errorCard.className = 'card';
    const title = document.createElement('b');
    title.textContent = 'No pudimos cargar las estadías';
    const detail = document.createElement('p');
    detail.className = 'muted';
    detail.textContent = 'La sesión sigue activa. Reintentá recargando la página.';
    errorCard.append(title, detail);
    list.appendChild(errorCard);
  }

  async function loadManagerStays(accessToken) {
    const response = await fetch(BACKEND_STAYS_URL, {
      method: 'GET',
      mode: 'cors',
      cache: 'no-store',
      headers: {
        Authorization: 'Bearer ' + accessToken,
        Accept: 'application/json'
      }
    });

    let body = null;
    try { body = await response.json(); } catch (_) {}

    if (!response.ok || !body || body.ok !== true || !Array.isArray(body.stays)) {
      const error = body && body.error ? String(body.error) : 'MANAGER_STAYS_LOAD_FAILED';
      const e = new Error(error);
      e.code = error;
      throw e;
    }

    renderStays(body.stays);
    return body.stays;
  }

  async function verifyManagerSession(accessToken) {
    const response = await fetch(BACKEND_SESSION_URL, {
      method: 'GET',
      mode: 'cors',
      cache: 'no-store',
      headers: {
        Authorization: 'Bearer ' + accessToken,
        Accept: 'application/json'
      }
    });

    let body = null;
    try { body = await response.json(); } catch (_) {}

    if (!response.ok || !body || body.ok !== true || !body.session) {
      const error = body && body.error ? String(body.error) : 'MANAGER_SESSION_DENIED';
      const e = new Error(error);
      e.code = error;
      throw e;
    }

    return body.session;
  }

  async function signIn(loginEmail, loginPassword) {
    const response = await fetch(
      SUPABASE_URL + '/auth/v1/token?grant_type=password',
      {
        method: 'POST',
        cache: 'no-store',
        headers: {
          apikey: SUPABASE_PUBLISHABLE_KEY,
          'Content-Type': 'application/json',
          Accept: 'application/json'
        },
        body: JSON.stringify({
          email: loginEmail,
          password: loginPassword
        })
      }
    );

    let body = null;
    try { body = await response.json(); } catch (_) {}

    if (!response.ok || !body || !body.access_token) {
      const e = new Error('LOGIN_INVALID');
      e.code = 'LOGIN_INVALID';
      throw e;
    }

    return body.access_token;
  }

  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    submit.disabled = true;
    setStatus('Verificando acceso…');

    try {
      const accessToken = await signIn(email.value.trim(), password.value);
      const managerSession = await verifyManagerSession(accessToken);
      sessionStorage.setItem(TOKEN_KEY, accessToken);
      password.value = '';
      setStatus('', '');
      showPanel(managerSession);
      loadManagerProperties(accessToken).catch(renderPropertiesError);
      loadManagerStays(accessToken).catch(renderStaysError);
    } catch (error) {
      clearToken();

      if (error && error.code === 'LOGIN_INVALID') {
        setStatus('Email o contraseña incorrectos.', 'error');
      } else if (error && error.code === 'WEB_IDENTITY_UNKNOWN') {
        setStatus('El usuario existe, pero todavía no está vinculado a un manager de Concierge.', 'error');
      } else if (error && error.code === 'MANAGER_MEMBER_NOT_ACTIVE') {
        setStatus('El acceso de este manager no está activo.', 'error');
      } else {
        setStatus('No se pudo validar el acceso. Revisaremos la conexión antes de continuar.', 'error');
      }
    } finally {
      submit.disabled = false;
    }
  });

  logout.addEventListener('click', () => {
    showLogin('');
  });

  (async () => {
    const existingToken = sessionStorage.getItem(TOKEN_KEY);
    if (!existingToken) {
      showLogin('');
      return;
    }

    setStatus('Restaurando sesión…');

    try {
      const managerSession = await verifyManagerSession(existingToken);
      setStatus('', '');
      showPanel(managerSession);
      loadManagerProperties(existingToken).catch(renderPropertiesError);
      loadManagerStays(existingToken).catch(renderStaysError);
    } catch (_) {
      showLogin('Tu sesión venció. Iniciá sesión nuevamente.');
    }
  })();
})();
`;

fs.writeFileSync(path.join(managerDir, 'manager-auth.js'), browserJs);

let html = fs.readFileSync(indexFile, 'utf8');

html = html.replace(
  '<link rel="stylesheet" href="/manager/manager.css">',
  '<link rel="stylesheet" href="/manager/manager.css">\n  <link rel="stylesheet" href="/manager/manager-auth.css">'
);

html = html.replace(
  '<body>',
  `<body class="manager-auth-pending">
  <section class="manager-auth-screen" id="manager-auth" aria-labelledby="manager-login-title">
    <div class="manager-auth-card">
      <div class="manager-auth-brand">Che<span>bot</span> Concierge</div>
      <div class="manager-auth-kicker">Manager Web V1 · Beta interna</div>
      <h1 id="manager-login-title">Ingresá a tu panel</h1>
      <p>Acceso exclusivo para managers autorizados de Chebot Concierge.</p>
      <form id="manager-login-form" autocomplete="on">
        <div class="manager-auth-field">
          <label for="manager-email">Email</label>
          <input id="manager-email" name="email" type="email" autocomplete="username" required>
        </div>
        <div class="manager-auth-field">
          <label for="manager-password">Contraseña</label>
          <input id="manager-password" name="password" type="password" autocomplete="current-password" required>
        </div>
        <button class="manager-auth-submit" id="manager-login-submit" type="submit">Ingresar</button>
        <div class="manager-auth-status" id="manager-auth-status" role="status" aria-live="polite"></div>
      </form>
      <p class="manager-auth-foot">Preview aislada. La contraseña se envía directamente a Supabase Auth y no se guarda en el sitio.</p>
    </div>
  </section>`
);

html = html.replace(
  '<strong>Vicky & Maty · Demo</strong>\n        <span class="pill">Modo manager · WhatsApp-first</span>',
  `<strong id="manager-account-label">Chebot Concierge · Manager</strong>
        <div><span class="manager-auth-session" id="manager-session-label">Sesión verificada</span><button class="manager-auth-logout" id="manager-logout" type="button">Salir</button></div>`
);

html = html.replace(
  '<b>Preview interna:</b> interfaz ficticia y aislada. El acceso real, autenticación y datos vivos se conectarán al backend Concierge en una etapa posterior.',
  '<b>Preview autenticada:</b> acceso, Propiedades y Estadías ya usan datos reales de Chebot Concierge Dev. Las demás secciones continúan con datos ficticios de demostración.'
);

html = html.replace(
  'Preview con datos ficticios. Sin secretos ni información real de huéspedes.',
  'Preview autenticada. Propiedades y Estadías: datos reales QA. Resto del panel: demostración.'
);

html = html.replace(
  'Chebot Concierge Manager Web V1 · Preview interna · Datos ficticios · Sin secretos reales.',
  'Chebot Concierge Manager Web V1 · Preview autenticada · Propiedades y Estadías reales QA · Sin secretos reales.'
);

html = html.replace(
  '</body>',
  '  <script src="/manager/manager-auth.js" defer></script>\n</body>'
);

fs.writeFileSync(indexFile, html);
console.log('Manager Web auth gate installed.');
